# Generated by Django 4.0.5 on 2022-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answers', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
