# Generated by Django 4.0.5 on 2022-07-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VenusFlytrap', '0002_korisnik'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='answers',
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(to='VenusFlytrap.answer', verbose_name='list of answer '),
        ),
    ]
